Upgrade to python3, C code cleanup.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3499,26 +3499,26 @@ then
 	fi
 
 	for ac_header in $PYDEV/Python.h
-do :
-  as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
-ac_fn_c_check_header_mongrel "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
-eval as_val=\$$as_ac_Header
-   if test "x$as_val" = x""yes; then :
-  cat >>confdefs.h <<_ACEOF
+	do :
+	  as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
+	  ac_fn_c_check_header_mongrel "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
+	  eval as_val=\$$as_ac_Header
+	  if test "x$as_val" = x""yes; then :
+	    cat >>confdefs.h <<_ACEOF
 #define `$as_echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
-else
-  echo "error: missing python header files" && exit 1
-fi
+	  else
+	    echo "error: missing python header files" && exit 1
+	  fi
 
-done
+	done
 
 
 	if ! test $PYLIB
 	then
-				echo "import sys" > pylib.py
-		echo "for path in sys.path: print path" >> pylib.py
+		echo "import sys" > pylib.py
+		echo "for path in sys.path: print(path)" >> pylib.py
 		PYLIB="$(python pylib.py | grep -e '-packages$' | head -1)"
 		rm -f pylib.py
 	fi
